#define COMBO_COUNT 0
#define IGNORE_MOD_TAP_INTERRUPT
#define IGNORE_MOD_TAP_INTERRUPT_PER_KEY
#define TAPPING_TERM 150
#define TAPPING_TERM_PER_KEY
#define RETRO_TAPPING
#define RETRO_TAPPING_PER_KEY
/* #define PERMISSIVE_HOLD */
/* #define PERMISSIVE_HOLD_PER_KEY */
